// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | HomepageFeaturedProductsX4Slice
  | FeaturedProductTwoSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProductDocumentDataSlicesSlice = ProductPageIntegrationFieldSlice;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Shopify Product field in *Product*
   *
   * - **Field Type**: Integration Fields (Catalog: `shopify-integration-v1--prismic_2`)
   * - **Placeholder**: *None*
   * - **API ID Path**: product.shopify_product
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  shopify_product: prismic.IntegrationField;

  /**
   * Price field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

export type AllDocumentTypes = PageDocument | ProductDocument;

/**
 * Primary content in *HomepageFeaturedProduct → Default → Primary*
 */
export interface FeaturedProductTwoSliceDefaultPrimary {
  /**
   * Image field in *HomepageFeaturedProduct → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_product_two.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Product field in *HomepageFeaturedProduct → Default → Primary*
   *
   * - **Field Type**: Integration Fields (Catalog: `shopify-integration-v1--prismic_2`)
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_product_two.default.primary.product
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  product: prismic.IntegrationField;
}

/**
 * Default variation for HomepageFeaturedProduct Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductTwoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProductTwoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomepageFeaturedProduct*
 */
type FeaturedProductTwoSliceVariation = FeaturedProductTwoSliceDefault;

/**
 * HomepageFeaturedProduct Shared Slice
 *
 * - **API ID**: `featured_product_two`
 * - **Description**: FeaturedProductTwo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductTwoSlice = prismic.SharedSlice<
  "featured_product_two",
  FeaturedProductTwoSliceVariation
>;

/**
 * Primary content in *HomepageFeaturedProductsX4 → Default → Primary*
 */
export interface HomepageFeaturedProductsX4SliceDefaultPrimary {
  /**
   * Product 1 field in *HomepageFeaturedProductsX4 → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_featured_products_x4.default.primary.product
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product: prismic.ContentRelationshipField<"product">;

  /**
   * Product 2 field in *HomepageFeaturedProductsX4 → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_featured_products_x4.default.primary.product_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product_2: prismic.ContentRelationshipField<"product">;

  /**
   * Product 3 field in *HomepageFeaturedProductsX4 → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_featured_products_x4.default.primary.product_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product_3: prismic.ContentRelationshipField<"product">;

  /**
   * Product 4 field in *HomepageFeaturedProductsX4 → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_featured_products_x4.default.primary.product_4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product_4: prismic.ContentRelationshipField<"product">;
}

/**
 * Default variation for HomepageFeaturedProductsX4 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomepageFeaturedProductsX4SliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<HomepageFeaturedProductsX4SliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *HomepageFeaturedProductsX4*
 */
type HomepageFeaturedProductsX4SliceVariation =
  HomepageFeaturedProductsX4SliceDefault;

/**
 * HomepageFeaturedProductsX4 Shared Slice
 *
 * - **API ID**: `homepage_featured_products_x4`
 * - **Description**: HomepageFeaturedProductsX4
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomepageFeaturedProductsX4Slice = prismic.SharedSlice<
  "homepage_featured_products_x4",
  HomepageFeaturedProductsX4SliceVariation
>;

/**
 * Primary content in *Product → Default → Primary*
 */
export interface ProductSliceDefaultPrimary {
  /**
   * Image field in *Product → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Product field in *Product → Default → Primary*
   *
   * - **Field Type**: Integration Fields (Catalog: `shopify-integration-v1--prismic_2`)
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.product
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  product: prismic.IntegrationField;
}

/**
 * Default variation for Product Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Product*
 */
type ProductSliceVariation = ProductSliceDefault;

/**
 * Product Shared Slice
 *
 * - **API ID**: `product`
 * - **Description**: Product
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductSlice = prismic.SharedSlice<
  "product",
  ProductSliceVariation
>;

/**
 * Primary content in *ProductPageIntegrationField → Default → Primary*
 */
export interface ProductPageIntegrationFieldSliceDefaultPrimary {
  /**
   * Product field in *ProductPageIntegrationField → Default → Primary*
   *
   * - **Field Type**: Integration Fields (Catalog: `shopify-integration-v1--prismic_2`)
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page_integration_field.default.primary.product
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  product: prismic.IntegrationField;
}

/**
 * Default variation for ProductPageIntegrationField Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductPageIntegrationFieldSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<ProductPageIntegrationFieldSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *ProductPageIntegrationField*
 */
type ProductPageIntegrationFieldSliceVariation =
  ProductPageIntegrationFieldSliceDefault;

/**
 * ProductPageIntegrationField Shared Slice
 *
 * - **API ID**: `product_page_integration_field`
 * - **Description**: ProductPageIntegrationField
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductPageIntegrationFieldSlice = prismic.SharedSlice<
  "product_page_integration_field",
  ProductPageIntegrationFieldSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataSlicesSlice,
      AllDocumentTypes,
      FeaturedProductTwoSlice,
      FeaturedProductTwoSliceDefaultPrimary,
      FeaturedProductTwoSliceVariation,
      FeaturedProductTwoSliceDefault,
      HomepageFeaturedProductsX4Slice,
      HomepageFeaturedProductsX4SliceDefaultPrimary,
      HomepageFeaturedProductsX4SliceVariation,
      HomepageFeaturedProductsX4SliceDefault,
      ProductSlice,
      ProductSliceDefaultPrimary,
      ProductSliceVariation,
      ProductSliceDefault,
      ProductPageIntegrationFieldSlice,
      ProductPageIntegrationFieldSliceDefaultPrimary,
      ProductPageIntegrationFieldSliceVariation,
      ProductPageIntegrationFieldSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
