// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_product_two: dynamic(() => import("./HomepageFeaturedProduct")),
  homepage_featured_products_x4: dynamic(
    () => import("./HomepageFeaturedProductsX4"),
  ),
  product: dynamic(() => import("./Product")),
  product_page_integration_field: dynamic(
    () => import("./ProductPageIntegrationField"),
  ),
  rich_text: dynamic(() => import("./RichText")),
};
